# Generated by Django 5.2.1 on 2025-06-13 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostIDReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('document_type', models.CharField(choices=[('ID', 'ID Card'), ('Passport', 'Passport'), ('License', 'Driving License')], max_length=50)),
                ('lost_location', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('found_by', models.CharField(max_length=100)),
                ('scanned_image', models.ImageField(upload_to='lost_ids/')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('collector', 'Collector'), ('sponsor', 'Sponsor')], max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('found_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapiid.lostidreport')),
            ],
        ),
    ]
